### ISSUE TITLE
Error buiding code on ubuntu

### ISSUE THREAD

**Issue by pelcom** [wiomoc/whatsappweb-rs#7]
I can see so much work has been done to develop this library.
Thanks so much  @wiomoc  for sharing.

I am very new to rust and i get the below error when i run "cargo build" am i missing something?

   Compiling whatsappweb v0.0.1 (file:///root/whatsappweb-rs)
error: failed to run custom build command for `whatsappweb v0.0.1 (file:///root/whatsappweb-rs)`
process didn't exit successfully: `/root/whatsappweb-rs/target/debug/build/whatsappweb-9448639d0a83eb2e/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'protoc: Custom { kind: NotFound, error: StringError("failed to spawn `\"protoc\" \"--version\"`: No such file or directory (os error 2)") }', libcore/result.rs:945:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:463
   5: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:350
   6: rust_begin_unwind
             at libstd/panicking.rs:328
   7: core::panicking::panic_fmt
             at libcore/panicking.rs:71
   8: core::result::unwrap_failed
             at /checkout/src/libcore/macros.rs:26
   9: <core::result::Result<T, E>>::expect
             at /checkout/src/libcore/result.rs:809
  10: build_script_build::main
             at ./build.rs:4
  11: std::rt::lang_start::{{closure}}
             at /checkout/src/libstd/rt.rs:74
  12: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  13: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:105
  14: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:374
             at libstd/rt.rs:58
  15: std::rt::lang_start
             at /checkout/src/libstd/rt.rs:74
  16: main
  17: __libc_start_main
  18: _start

**Comment by wiomoc** [comment]
> am i missing something?

Yep, you're missing protoc
Just install it with ```apt-get install protobuf-compiler```

**Comment by pelcom** [comment]
thanks.
